version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-positions-ui:
    container_name: reporting-hub-bop-positions-ui
    image: mojaloop/reporting-hub-bop-positions-ui
    build:
      context: .
      cache_from:
        - mojaloop/reporting-hub-bop-positions-ui
    environment:
      - CENTRAL_LEDGER_ENDPOINT=http://localhost:3001
    ports:
      - "8084:8084"
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:8084 -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
