apiVersion: v1
kind: Service
metadata:
  name: reporting-hub-bop-positions-ui
  labels:
    app.kubernetes.io/name: reporting-hub-bop-positions-ui
spec:
  ports:
  - port: 80
    targetPort: 8084
    name: http
  selector:
    app.kubernetes.io/name: reporting-hub-bop-positions-ui
